use crate::api::{Game, Review, User};

pub fn get_mock_games() -> Vec<Game> {
    vec![
        Game {
            id: 1,
            title: "Baldur's Gate 3".to_string(),
            slug: "baldurs-gate-3".to_string(),
            description: Some("An epic fantasy RPG with mind-bending storytelling and endless possibilities.".to_string()),
            genre: Some("RPG".to_string()),
            platform: Some("PC, PlayStation".to_string()),
            release_date: Some("2023-08-03".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co6i6c.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.8),
            review_count: 3,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 2,
            title: "Elden Ring".to_string(),
            slug: "elden-ring".to_string(),
            description: Some("A challenging action RPG set in a vast open world with breathtaking vistas.".to_string()),
            genre: Some("Action RPG".to_string()),
            platform: Some("PC, PlayStation, Xbox".to_string()),
            release_date: Some("2022-02-25".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co5kwa.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.9),
            review_count: 2,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 3,
            title: "Starfield".to_string(),
            slug: "starfield".to_string(),
            description: Some("Embark on an epic space exploration adventure across hundreds of star systems.".to_string()),
            genre: Some("Action RPG".to_string()),
            platform: Some("PC, Xbox".to_string()),
            release_date: Some("2023-09-06".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co5yjs.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.2),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 4,
            title: "Hollow Knight".to_string(),
            slug: "hollow-knight".to_string(),
            description: Some("A hauntingly beautiful metroidvania about a small knight exploring a mysterious kingdom.".to_string()),
            genre: Some("Metroidvania".to_string()),
            platform: Some("PC, Nintendo Switch".to_string()),
            release_date: Some("2017-02-24".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co5fmg.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.7),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 5,
            title: "The Legend of Zelda: Tears of the Kingdom".to_string(),
            slug: "zelda-totk".to_string(),
            description: Some("Link's latest adventure in a sprawling kingdom filled with secrets and puzzles.".to_string()),
            genre: Some("Action Adventure".to_string()),
            platform: Some("Nintendo Switch".to_string()),
            release_date: Some("2023-05-12".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co6okg.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.9),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 6,
            title: "Hades".to_string(),
            slug: "hades".to_string(),
            description: Some("A roguelike dungeon crawler with incredible art, music, and storytelling.".to_string()),
            genre: Some("Roguelike".to_string()),
            platform: Some("PC, Nintendo Switch".to_string()),
            release_date: Some("2020-09-17".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co2pyt.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.8),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 7,
            title: "Stray".to_string(),
            slug: "stray".to_string(),
            description: Some("Play as a cat in a neon-lit cyberpunk city and uncover its mysteries.".to_string()),
            genre: Some("Adventure".to_string()),
            platform: Some("PC, PlayStation".to_string()),
            release_date: Some("2022-07-19".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co5wnq.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.6),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
        Game {
            id: 8,
            title: "Cyberpunk 2077".to_string(),
            slug: "cyberpunk-2077".to_string(),
            description: Some("An immersive open-world RPG set in a dystopian future city.".to_string()),
            genre: Some("Action RPG".to_string()),
            platform: Some("PC, PlayStation, Xbox".to_string()),
            release_date: Some("2020-12-10".to_string()),
            cover_image_url: Some("https://images.igdb.com/igdb/image/upload/t_cover_big/co1wup.jpg".to_string()),
            rawg_id: None,
            avg_rating: Some(4.1),
            review_count: 1,
            created_at: "2024-01-01T00:00:00".to_string(),
            updated_at: "2024-01-01T00:00:00".to_string(),
        },
    ]
}

pub fn get_mock_reviews() -> Vec<Review> {
    vec![
        Review {
            id: 1,
            user_id: 1,
            game_id: 1,
            rating: 5,
            title: Some("Masterpiece!".to_string()),
            body: "This game is absolutely incredible. Every moment is magical and I couldn't put it down.".to_string(),
            created_at: "2024-02-01T10:00:00".to_string(),
            updated_at: "2024-02-01T10:00:00".to_string(),
            username: "alexgamer".to_string(),
            display_name: Some("Alex Gamer".to_string()),
        },
        Review {
            id: 2,
            user_id: 2,
            game_id: 1,
            rating: 4,
            title: Some("Fantastic Adventure".to_string()),
            body: "Amazing gameplay and story, though it could use some optimization. Still worth playing!".to_string(),
            created_at: "2024-02-02T14:30:00".to_string(),
            updated_at: "2024-02-02T14:30:00".to_string(),
            username: "luna_midnight".to_string(),
            display_name: Some("Luna".to_string()),
        },
        Review {
            id: 3,
            user_id: 1,
            game_id: 2,
            rating: 5,
            title: Some("Gaming Perfection".to_string()),
            body: "Elden Ring redefined what open-world RPGs can be. Stunning exploration and challenging combat!".to_string(),
            created_at: "2024-02-03T09:15:00".to_string(),
            updated_at: "2024-02-03T09:15:00".to_string(),
            username: "alexgamer".to_string(),
            display_name: Some("Alex Gamer".to_string()),
        },
        Review {
            id: 4,
            user_id: 2,
            game_id: 2,
            rating: 5,
            title: Some("Challenging & Rewarding".to_string()),
            body: "The difficulty is punishing but fair. Every victory feels earned. Truly masterful design.".to_string(),
            created_at: "2024-02-04T16:45:00".to_string(),
            updated_at: "2024-02-04T16:45:00".to_string(),
            username: "luna_midnight".to_string(),
            display_name: Some("Luna".to_string()),
        },
        Review {
            id: 5,
            user_id: 1,
            game_id: 3,
            rating: 4,
            title: Some("Space Exploration Done Right".to_string()),
            body: "A massive game with incredible ambition. Worth the journey despite some rough edges.".to_string(),
            created_at: "2024-02-05T11:20:00".to_string(),
            updated_at: "2024-02-05T11:20:00".to_string(),
            username: "alexgamer".to_string(),
            display_name: Some("Alex Gamer".to_string()),
        },
        Review {
            id: 6,
            user_id: 2,
            game_id: 4,
            rating: 5,
            title: Some("Indie Masterpiece".to_string()),
            body: "Small indie game with massive heart. Beautiful pixel art and atmospheric music throughout.".to_string(),
            created_at: "2024-02-06T13:50:00".to_string(),
            updated_at: "2024-02-06T13:50:00".to_string(),
            username: "luna_midnight".to_string(),
            display_name: Some("Luna".to_string()),
        },
        Review {
            id: 7,
            user_id: 1,
            game_id: 5,
            rating: 5,
            title: Some("A Link to Excellence".to_string()),
            body: "Link's adventure continues to amaze. Creative puzzles and endless exploration opportunities.".to_string(),
            created_at: "2024-02-07T10:30:00".to_string(),
            updated_at: "2024-02-07T10:30:00".to_string(),
            username: "alexgamer".to_string(),
            display_name: Some("Alex Gamer".to_string()),
        },
        Review {
            id: 8,
            user_id: 2,
            game_id: 6,
            rating: 5,
            title: Some("Roguelike Perfection".to_string()),
            body: "Hades proves roguelikes can have amazing story AND great gameplay. Addictive runs!".to_string(),
            created_at: "2024-02-08T15:20:00".to_string(),
            updated_at: "2024-02-08T15:20:00".to_string(),
            username: "luna_midnight".to_string(),
            display_name: Some("Luna".to_string()),
        },
        Review {
            id: 9,
            user_id: 1,
            game_id: 7,
            rating: 5,
            title: Some("A Unique Experience".to_string()),
            body: "Playing as a cat in this world is delightful. Unexpected gem with great atmosphere.".to_string(),
            created_at: "2024-02-09T12:00:00".to_string(),
            updated_at: "2024-02-09T12:00:00".to_string(),
            username: "alexgamer".to_string(),
            display_name: Some("Alex Gamer".to_string()),
        },
        Review {
            id: 10,
            user_id: 2,
            game_id: 8,
            rating: 4,
            title: Some("Much Improved".to_string()),
            body: "The updates have made this game so much better. Great RPG experience now!".to_string(),
            created_at: "2024-02-10T08:45:00".to_string(),
            updated_at: "2024-02-10T08:45:00".to_string(),
            username: "luna_midnight".to_string(),
            display_name: Some("Luna".to_string()),
        },
    ]
}

pub fn get_mock_users() -> Vec<User> {
    vec![
        User {
            id: 1,
            username: "alexgamer".to_string(),
            email: "alex@example.com".to_string(),
            display_name: Some("Alex Gamer".to_string()),
            avatar_url: Some("https://api.dicebear.com/7.x/avataaars/svg?seed=Alex".to_string()),
            created_at: "2024-01-01T00:00:00".to_string(),
        },
        User {
            id: 2,
            username: "luna_midnight".to_string(),
            email: "luna@example.com".to_string(),
            display_name: Some("Luna".to_string()),
            avatar_url: Some("https://api.dicebear.com/7.x/avataaars/svg?seed=Luna".to_string()),
            created_at: "2024-01-01T00:00:00".to_string(),
        },
    ]
}
